#!/usr/bin/env python3
"""release.py — SemVer release management & automated CHANGELOG generator from checkpoint tags."""

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

CONSUMED_CLI_SURFACE = [
    "scripts/init_project.py",
    "scripts/fetch_next_work.py",
    "scripts/fetch_next_issue.py",
    "scripts/claim_issue.py",
    "scripts/create_branch.py",
    "scripts/create_pr.py",
    "scripts/check_ci.py",
    "scripts/fetch_pr_feedback.py",
    "scripts/update_issue_status.py",
    "scripts/merge_pr.py",
    "scripts/triage_backlog.py",
    "scripts/enable_main_ruleset.py",
    "scripts/install_local_agent_integrations.sh",
    "scripts/install_cursor_integration.sh",
    "scripts/release.py",
]


def run_cmd(cmd, cwd=None):
    res = subprocess.run(cmd, capture_output=True, text=True, cwd=cwd or str(ROOT))
    return res.returncode, res.stdout.strip(), res.stderr.strip()


def validate_semver(tag: str) -> bool:
    """Validate that tag follows vX.Y.Z SemVer format."""
    return bool(re.match(r"^v\d+\.\d+\.\d+$", tag))


def get_checkpoint_tags():
    """Retrieve all ckpt/* tags and their annotation/subject messages."""
    code, stdout, _ = run_cmd(["git", "tag", "-l", "ckpt/*", "--format=%(refname:short)|%(contents:subject)"])
    if code != 0 or not stdout:
        return []

    checkpoints = []
    for line in stdout.splitlines():
        if "|" in line:
            tag_name, subject = line.split("|", 1)
            checkpoints.append({"tag": tag_name, "subject": subject})
    return checkpoints


def generate_changelog_content() -> str:
    """Generate Markdown content for CHANGELOG.md based on checkpoint tags and git history."""
    checkpoints = get_checkpoint_tags()
    lines = [
        "# CHANGELOG",
        "",
        "All notable changes to **Aru_Agentic_SDLC** are documented here.",
        "This file is automatically generated from `ckpt/*` tags and git checkpoints.",
        "",
        "## Consumed-CLI Surface",
        "",
        "The following scripts constitute the supported consumer-facing CLI surface.",
        "Breaking changes (renames, mandatory flags, exit contract changes) force a **MAJOR** version bump.",
        "",
    ]
    for script in CONSUMED_CLI_SURFACE:
        lines.append(f"- `{script}`")

    lines.append("")
    lines.append("## Checkpoint History")
    lines.append("")

    if not checkpoints:
        lines.append("No `ckpt/*` tags found.")
    else:
        for ckpt in reversed(checkpoints):
            lines.append(f"- **{ckpt['tag']}**: {ckpt['subject']}")

    lines.append("")
    return "\n".join(lines)


def write_changelog(dry_run: bool = False) -> str:
    content = generate_changelog_content()
    if not dry_run:
        changelog_path = ROOT / "CHANGELOG.md"
        changelog_path.write_text(content, encoding="utf-8")
    return content


def create_release_tag(tag: str, dry_run: bool = False) -> int:
    if not validate_semver(tag):
        print(f"error: '{tag}' is not a valid SemVer tag (must match vX.Y.Z).", file=sys.stderr)
        return 1

    cmd = ["git", "tag", "-a", tag, "-m", f"Release {tag}"]
    if dry_run:
        print(f"[DRY-RUN] Would run: {' '.join(cmd)}")
        return 0

    code, stdout, stderr = run_cmd(cmd)
    if code != 0:
        print(f"error: failed to create tag '{tag}': {stderr}", file=sys.stderr)
        return 1

    print(f"✅ Created release tag '{tag}'.")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description="SemVer release & CHANGELOG generator for Aru_Agentic_SDLC")
    parser.add_argument("--generate-changelog", action="store_true", help="Generate CHANGELOG.md from checkpoint tags")
    parser.add_argument("--tag", type=str, help="Create an annotated SemVer release tag (e.g. v0.1.0)")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without modifying disk or git tags")
    parser.add_argument("--check", action="store_true", help="Check current version and release status")

    args = parser.parse_args(argv)

    if args.check:
        code, stdout, _ = run_cmd(["git", "tag", "-l", "v*", "--sort=-v:refname"])
        tags = stdout.splitlines() if stdout else []
        print(f"Latest release tags: {tags[:5] if tags else 'None'}")
        return 0

    if args.generate_changelog:
        content = write_changelog(dry_run=args.dry_run)
        if args.dry_run:
            print("[DRY-RUN] Generated CHANGELOG content:\n")
            print(content)
        else:
            print("✅ Updated CHANGELOG.md")

    if args.tag:
        return create_release_tag(args.tag, dry_run=args.dry_run)

    if not (args.generate_changelog or args.tag or args.check):
        parser.print_help()

    return 0


if __name__ == "__main__":
    sys.exit(main())
