"""Bounded supported account reads. Never reads credential files or buys resets."""
from __future__ import annotations

import json
import os
from pathlib import Path
import selectors
import subprocess
import tempfile
import time

from .config import DriverError
from . import quota

def codex_read(prefix, cwd, timeout=20):
    """Validate actual responses against schemas generated by this exact binary."""
    try:
        import jsonschema
    except ImportError:
        raise DriverError("quota-schema-validator-unavailable") from None
    deadline = time.monotonic() + timeout
    with tempfile.TemporaryDirectory(prefix="aru-quota-schema-") as directory:
        schema_run = subprocess.run(  # nosemgrep: python.lang.security.audit.dangerous-subprocess-use-audit
            [*prefix, "app-server", "generate-json-schema", "--out", directory], cwd=cwd,
            stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            timeout=max(.01, deadline - time.monotonic()), check=False)
        if schema_run.returncode:
            raise DriverError("quota-schema-unavailable")
        schemas = installed_schemas(directory, jsonschema)
        process = subprocess.Popen(  # nosemgrep: python.lang.security.audit.dangerous-subprocess-use-audit
            [*prefix, "app-server", "--stdio"], cwd=cwd, stdin=subprocess.PIPE,
            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, start_new_session=True)
        try:
            with selectors.DefaultSelector() as selector:
                selector.register(process.stdout, selectors.EVENT_READ)

                rpc = Reader(process, selector, deadline).call
                rpc(1, "initialize", {"clientInfo": {"name": "aru_quota", "version": "1"}, "capabilities": {}})
                process.stdin.write(b'{"method":"initialized"}\n')
                process.stdin.flush()
                before = rpc(2, "account/read", {"refreshToken": False})
                limits = rpc(3, "account/rateLimits/read", {"excludeResetCreditDetails": True})
                after = rpc(4, "account/read", {"refreshToken": False})
                for value, name in ((before, "GetAccountResponse"), (after, "GetAccountResponse"),
                                    (limits, "GetAccountRateLimitsResponse")):
                    try:
                        jsonschema.validate(value, schemas[name])
                    except jsonschema.ValidationError:
                        raise DriverError("quota-protocol-invalid") from None
                if before != after:
                    raise DriverError("quota-account-changed")
                return before, limits
        finally:
            process.stdin.close()
            process.stdout.close()
            process.terminate()
            try:
                process.wait(timeout=2)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait(timeout=2)

def installed_schemas(directory, jsonschema):
    schemas = {}
    for name in ("GetAccountResponse", "GetAccountRateLimitsResponse"):
        try:
            schemas[name] = json.loads((Path(directory) / "v2" / (name + ".json")).read_text())
            jsonschema.Draft7Validator.check_schema(schemas[name])
        except (OSError, ValueError, jsonschema.SchemaError):
            raise DriverError("quota-schema-invalid") from None
    return schemas

def normalize(lane, account, limits, now):
    q = lane["quota"]
    result = quota.unknown(lane, now, "identity-unavailable")
    account_id = limits.get("accountId")
    if not isinstance(account_id, str) or not account_id or (account.get("account") or {}).get("type") != "chatgpt":
        return result
    if quota.digest(account_id) != q["account_sha256"]:
        raise DriverError("quota-account-mismatch")
    result.update(source="codex-app-server", identity_verified=True)
    pools = limits.get("rateLimitsByLimitId")
    if pools is None:
        pools = {limits["rateLimits"].get("limitId"): limits["rateLimits"]}
    if not isinstance(pools, dict) or not all(isinstance(v, dict) for v in pools.values()):
        raise DriverError("quota-pools-invalid")
    selected = pools.get(q["pool"])
    if not selected:
        return {**result, "reason": "pool-unavailable"}
    if selected.get("limitId") != q["pool"] or selected.get("normalModelSlug") not in {None, q["model"]}:
        raise DriverError("quota-model-pool-mismatch")
    old = limits["rateLimits"]
    if old.get("limitId") == q["pool"] and old != selected:
        raise DriverError("quota-pools-contradictory")
    if selected.get("individualLimit") is not None:
        return {**result, "reason": "additional-spend-window-unsupported"}
    windows = normalize_windows(selected, q)
    result["windows"] = windows
    blocked = (limits.get("ordinaryUsageAllowed") is False or selected.get("spendControlReached") is True
               or selected.get("rateLimitReachedType") is not None)
    if blocked or any(w["remaining"] == 0 for w in windows.values()):
        result.update(state="exhausted", confidence="provider", reason="provider-blocked" if blocked else "window-exhausted")
    elif set(windows) != set(q["windows"]) or limits.get("ordinaryUsageAllowed") is not True:
        result["reason"] = "windows-or-ordinary-usage-unknown"
    else:
        result.update(state="known", confidence="provider", reason="provider-observed")
    return result

def normalize_windows(selected, q):
    windows = {}
    for field in ("primary", "secondary"):
        w = selected.get(field)
        if w is None:
            continue
        if not isinstance(w, dict) or not quota.number(w.get("usedPercent"), 0, 100):
            raise DriverError("quota-window-invalid")
        if w.get("resetsAt") is None or w.get("windowDurationMins") is None:
            continue
        names = [n for n, duration in q["windows"].items() if duration == w["windowDurationMins"]]
        if len(names) != 1 or names[0] in windows:
            raise DriverError("quota-window-duration-invalid")
        name = names[0]
        windows[name] = {"unit": "percent", "remaining": 100 - w["usedPercent"],
                         "reset_at": w["resetsAt"], "duration_minutes": w["windowDurationMins"]}
    return windows

def collect(config, repo, identity):
    lane = config.lane(repo, identity)
    if lane["family"] != "openai-codex":
        reason = "claude-statusline-unavailable-in-print" if lane["family"] == "claude-code" else "supported-quota-surface-unavailable"
        return quota.unknown(lane, time.time(), reason)
    argv = lane["command"]
    try:
        prefix = argv[:argv.index("exec")]
        for index in range(argv.index("exec") + 1, len(argv) - 1):
            if argv[index] in {"--profile", "-p", "-c", "--config"}:
                prefix += argv[index:index + 2]
        account, limits = codex_read(prefix, config.project(repo)["repo_dir"])
        return normalize(lane, account, limits, time.time())
    except (OSError, subprocess.TimeoutExpired):
        return quota.unknown(lane, time.time(), "supported-cli-unavailable", unavailable=True)
    except DriverError as exc:
        if str(exc).endswith(("unavailable", "timeout")):
            return quota.unknown(lane, time.time(), str(exc), unavailable=True)
        raise
    except (ValueError, KeyError, TypeError):
        raise DriverError("quota-protocol-invalid") from None

class Reader:
    def __init__(self, process, selector, deadline):
        self.process, self.selector, self.deadline = process, selector, deadline
        self.buffer, self.total = b"", 0

    def call(self, identifier, method, params):
        self.process.stdin.write((json.dumps({"id": identifier, "method": method, "params": params}) + "\n").encode())
        self.process.stdin.flush()
        while time.monotonic() < self.deadline:
            while b"\n" in self.buffer:
                line, self.buffer = self.buffer.split(b"\n", 1)
                message = json.loads(line, object_pairs_hook=unique_fields)
                if not isinstance(message, dict):
                    raise DriverError("quota-protocol-invalid")
                if message.get("id") == identifier:
                    if "error" in message:
                        raise DriverError("quota-read-unavailable")
                    return message["result"]
            if not self.selector.select(max(.001, self.deadline - time.monotonic())):
                break
            chunk = os.read(self.process.stdout.fileno(), 65536)
            self.total += len(chunk)
            if not chunk or self.total > 1024 * 1024:
                raise DriverError("quota-protocol-unavailable")
            self.buffer += chunk
        raise DriverError("quota-read-timeout")

def unique_fields(pairs):
    result = {}
    for name, value in pairs:
        if name in result:
            raise DriverError("quota-protocol-contradictory-fields")
        result[name] = value
    return result
